### ISSUE TITLE
Configurable retry count and delay between connection

### ISSUE THREAD

**Issue by RadekVoltr** [asukiaaa/arduino-XboxControllerNotificationParser#1]
Hi

I have issues with the connection. Don't know why but especially in case that class is created dynamically on heap via New it sometimes makes problems connecting.

I found that increasing the delay and number of tries really helped in this situation.

What about having these two config items as properties on a class or optional #defines in code ?

Can I do a pull request?

be
Radek

![image](https://user-images.githubusercontent.com/22295123/195409557-05f4bbbd-8ace-4a1b-abd2-268b4e5d7f79.png)

**Comment by asukiaaa** [comment]
Do you want to mention about https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32?

I know the problem on connection.
It sometimes cannot connect to the controller without resetting.
I updated the code and call resetting on example project by referencing count of failing.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/blob/b412d8e6b158efbc1c04ed8e6657e3567c8669de/examples/connect/connect.ino#L29-L31

**Comment by RadekVoltr** [comment]
Hi

Yes, I am aware of that feature and it helped but still I have better and shorter turnaround with little bit higher delay and more retries before reset.

Best regards
Radek

**Comment by asukiaaa** [comment]
I added variables about that.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/commit/be7579cfe5aed8ad75c365bb1950daaea92654e7

Please create discussion thread on https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32 from next time.
