### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by vitoscape** [asukiaaa/arduino-XboxControllerNotificationParser#2]
Is it possible to get information about Xbox Controller battery charge level?

**Comment by asukiaaa** [comment]
You can but battery information is role of [the other notification (0x180f)](https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/blob/a0a8974bd0c61ae1b2a11532e74c472d72b065b5/src/XboxSeriesXControllerESP32_asukiaaa.hpp#L16).
I get the information with using other library.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/blob/a0a8974bd0c61ae1b2a11532e74c472d72b065b5/src/XboxSeriesXControllerESP32_asukiaaa.hpp#L517-L521

**Comment by vitoscape** [comment]
Thank you.
